### ISSUE TITLE
data signed with "node-rsa" module (nodejs) is not verified with this smart contract

### ISSUE THREAD

**Issue by marcocastignoli** [adriamb/SolRsaVerify#11]
this is the library: https://www.npmjs.com/package/node-rsa

for some reasons if i sign and verify in node, it's verified
but if I pass the values in this smart contract it returns 1

**Comment by marcocastignoli** [comment]
```
_data: "0xca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb"
_s: "0xa01cce2a0824ca21feea887d159cb220a5f6b4e57bd3920e2f5300409772152a808f0ac87de8b88d7fd5df0325f373fc1edade4e597aaaa2b5e8fb34b4d49ede"
_m: "0x00a58cfbda78b6b24a9495c0fda27f80b0a1db66807ffd092136721d40fba9317d687e41b80635b472d26019723f8ed635bfc5503ca6b090e7dfb870e7887f1e2d"
```

**Comment by rodrigolb01** [comment]
Having the same issue here. At first I've thought it was something about how JavaScript was passing the values to the contract instance but I've tried in many different ways like using buffers, strings, file and the results is always 1.  

Also "$ echo -n "hello world" | openssl dgst -sha256 -sign private.pem -out | xxd -p | tr -d \\n" the command in this line of the documentation doesn't work in either windows or linux cmd. I have to pass a file name to -out and even then the result returned isn't in hex as show in the step.

 Perhaps the documentation needs to be updated.

**Comment by ADrWondertainment** [comment]
> Having the same issue here. At first I've thought it was something about how JavaScript was passing the values to the contract instance but I've tried in many different ways like using buffers, strings, file and the results is always 1.
> 
> Also "$ echo -n "hello world" | openssl dgst -sha256 -sign private.pem -out | xxd -p | tr -d \n" the command in this line of the documentation doesn't work in either windows or linux cmd. I have to pass a file name to -out and even then the result returned isn't in hex as show in the step.
> 
> Perhaps the documentation needs to be updated.

same issue here, wondering if you guys have solved this one or find an alternative way to verify signature? @rodrigolb01 @marcocastignoli

**Comment by ADrWondertainment** [comment]
https://github.com/adria0/SolRsaVerify/issues/6#issuecomment-454405114
finished, turns out that we need to use hex"abcd...." instead of "0xabcd...." in solidity

**Comment by adria0** [comment]
> ```
> _data: "0xca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb"
> _s: "0xa01cce2a0824ca21feea887d159cb220a5f6b4e57bd3920e2f5300409772152a808f0ac87de8b88d7fd5df0325f373fc1edade4e597aaaa2b5e8fb34b4d49ede"
> _m: "0x00a58cfbda78b6b24a9495c0fda27f80b0a1db66807ffd092136721d40fba9317d687e41b80635b472d26019723f8ed635bfc5503ca6b090e7dfb870e7887f1e2d"
> ```

I'm also not able to test it @marcocastignoli , could you provide the code that that you used to generate the signature, please?

**Comment by ADrWondertainment** [comment]
> i used hex"abcd..." instead of "0xabcd..." and test passed, in your case i think replace 0x prefix to hex string may help.
by the way, i used solidity 0.8.19 and the original code failed to compile when the original text is long, so i comment the code in    function "memcpy" after the for loop which in my understanding is for safety check, but you should make sure your input is always right if you use the same way i do. @adria0
