### ISSUE TITLE
Is this contract deployed on testnet/mainnet?

### ISSUE THREAD

**Issue by elichai** [adriamb/SolRsaVerify#2]
Hey,

Is the library deployed on any ethereum chain?
If so what is the address?
(If it's deployed on multiple chains I would be grateful to get the addresses)

Thanks,
Elichai.

**Comment by elichai** [comment]
Thanks!
Is this code audited?
And do you know if there's any existing ASN.1 solidity parser?(So I could verify chain of trust too)

**Comment by adriamb** [comment]
No, the code is not audited by another, at this moment. About an ASN1 parser, I don't know any one, but could be a really interesting thing to have, sure. Let's me know if you discover any one.
