### ISSUE TITLE
Add usage instructions

### ISSUE THREAD

**Issue by masonforest** [adriamb/SolRsaVerify#3]
Hello 👋

Thanks for building this!

I'm still trying to get `pkcs1Sha256VerifyRaw` to verify a signature that I've generated.

I've added usage instructions [here](https://github.com/adriamb/SolRsaVerify/compare/master...masonforest:add-usage?expand=1) although `pkcs1Sha256VerifyRaw` is returning 1 instead of 0 :/ 

I've tried with and without padding the exponent and modulus.

Any other ideas of what I'm doing wrong?

Thanks!

**Comment by adriamb** [comment]
Hi! 👋

Sure, having some minimal instructions is a must!

From your example, I created a test file. I really don't know what failed exactly (except for the `-n` flag in echo),  so, please, check if the test helps you to find your error.

https://github.com/adriamb/SolRsaVerify/blob/master/test/openssl.js

**Comment by masonforest** [comment]
That did it! You're right I needed to add the `-n` flag to the `echo` command and also I didn't know how to extract the modulus from the public key.

I opened [a PR adding usage instructions](https://github.com/adriamb/SolRsaVerify/pull/5). Feedback very welcome. Thanks!

**Comment by masonforest** [comment]
Closed by https://github.com/adriamb/SolRsaVerify/pull/5 🙂
