### ISSUE TITLE
Possibility of modifying pkcs1Sha256Verify for vanilla RSA

### ISSUE THREAD

**Issue by xenomorph1096** [adriamb/SolRsaVerify#9]
*Not an actual 'Issue' per se*

I tried to use the contract for verifying RSA Signatures. Works as expected for pkcs1v1.5 signatures.

However, I would like to be able to verify a vanilla RSA signature, i.e., a Signature generated by simple hash^e (mod n). Could do provide some idea as to what modifications to your contract would be necessary to achieve this?

**Comment by wirasuta** [comment]
I believe the functionality of RSA operation is provided by this line
https://github.com/adria0/SolRsaVerify/blob/b927ddbee01cc29efb1bc139fedcd7eb1ef1ef9f/contracts/SolRsaVerify.sol#L103-L105

It calls the 0x00...05 contract which allows big integer modular exponentiation defined in [EIP-198](https://eips.ethereum.org/EIPS/eip-198). To achieve what you're looking for, you can call the contract directly with the appropriate parameters and compare it to the hash.

**Comment by xenomorph1096** [comment]
Ah! I see. Thanks for the information. Very useful.
